apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: message-app.dev
      http:
        paths:
          - path: /api/message/get
            pathType: Prefix
            backend:
              service:
                name: message-service
                port:
                  number: 5000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: front-end-service
                port:
                  number: 3000
